### ISSUE TITLE
?

### ISSUE THREAD

**Issue by alktbihd** [iSm1le/Naomi-Tanizaki#18]
> info: [DISCORD]: Vertex#7730 (196566551451795456) > 3rbPlus (310101477668552705)                                                                                                                                                              >> util:help >>>
error: [DISCORD]: Error in command util:help TypeError: discord.Util.resolveStri                                                                                                                                                             ng is not a function
    at CommandMessage.respond (/root/NM/Naomi-Tanizaki/node_modules/discord.js-c                                                                                                                                                             ommando/src/commands/message.js:248:26)
    at CommandMessage.reply (/root/NM/Naomi-Tanizaki/node_modules/discord.js-com                                                                                                                                                             mando/src/commands/message.js:351:15)
    at HelpCommand.run (/root/NM/Naomi-Tanizaki/node_modules/discord.js-commando                                                                                                                                                             /src/commands/util/help.js:97:29)
    at CommandMessage.run (/root/NM/Naomi-Tanizaki/node_modules/discord.js-comma                                                                                                                                                             ndo/src/commands/message.js:178:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error:  TypeError: discord.Util.resolveString is not a function
    at CommandMessage.respond (/root/NM/Naomi-Tanizaki/node_modules/discord.js-c                                                                                                                                                             ommando/src/commands/message.js:248:26)
    at CommandMessage.reply (/root/NM/Naomi-Tanizaki/node_modules/discord.js-com                                                                                                                                                             mando/src/commands/message.js:351:15)
    at CommandMessage.run (/root/NM/Naomi-Tanizaki/node_modules/discord.js-comma                                                                                                                                                             ndo/src/commands/message.js:220:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Whats wrong?

**Comment by palkx** [comment]
Try now do clean deps install from master tree and say if error persists.
